spring.application.name=sapce
spring.datasource.url=jdbc:mysql://localhost:3306/space
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

--razorpay
       razorpay.key.id=rzp_test_TZQuywZJ6l608x
       razorpay.key.secret=HjqxtDzHP5EImJ5krQ8Vlz3x